### ISSUE TITLE
How to  add ring-ssl?

### ISSUE THREAD

**Issue by JoePython1** [shakthimaan/guestbook#2]
I would like to add self signed TLS cert

**Comment by shakthimaan** [comment]
The usual practice is to setup nginx with HTTPS and setup a reverse proxy. Otherwise, please refer the following documentation:

http://stackoverflow.com/questions/24897037/clojure-compojure-ring-and-https

http://stackoverflow.com/questions/18432832/how-do-you-enable-https-and-http-https-redirects-in-ring-compojure
